### ISSUE TITLE
[Bug] 完成配置后无法进入应用

### ISSUE THREAD

**Issue by MangMax** [Richasy/RichasyAssistant#11]
### Bug description / Bug 描述

无法进入应用使用

### Reproduce steps / 复现问题的步骤

```plain text
填写对话模型和翻译配置后点击启动应用无反应
```

### Expected behavior / 预期行为

进入应用

### Screenshot / 截图

![recording](https://github.com/Richasy/RichasyAssistant/assets/68525017/31a5189e-dbd6-4dff-af45-53a13771eaaa)

### Application source / 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] Others / 其它

### System version

- [X] Windows 11 21H2 (Build 22000)
- [ ] Others / 其它

### Device / 运行设备

Desktop/桌面/台式机

### We are the world / 人人为我，我为人人

None

**Comment by Richasy** [comment]
请确认一下：
1. 你是否曾经安装过旧版本的小幻助理？是的话请卸载后重新安装
2. 你是否把应用的默认安装位置调到了其它盘？是的话请移回到系统盘

**Comment by MangMax** [comment]
我卸载后切换回默认安装位确实可以了，前提是所有配置都必须都填上，不知道我的个例还是原本的设计，如果是这样的话我觉得应该加点提示。初始配置界面貌似有两个小bug，首先语音配置界面没有填写的控件，然后是配置dall的时候无法正确读取到模型列表，没有出现对话模型界面类似的下拉框选项，进入应用后可以正常获取模型列表了

**Comment by lehhair** [comment]
我也有这个问题,我只是想把这个软件作为我使用的第三方api的客户端,并且我也只使用chatgpt,其他的不知道咋填写,打不开,已经卸载重装过了
