### ISSUE TITLE
[Bug] 对话模型名称无列表

### ISSUE THREAD

**Issue by sseaan** [Richasy/RichasyAssistant#15]
### Bug description / Bug 描述

对话模型名称无列表

### Reproduce steps / 复现问题的步骤

```plain text
1.打开应用
2.进入“设置”
3.点击“内核设置”中OpenAPI的“编辑配置”
4.点击“对话模型名称”
```

### Expected behavior / 预期行为

我不知道是否是因为我使用的是自部署的OneAPI导致的，如果是的话，希望添加支持或者增加自定义模型名称的功能

### Screenshot / 截图

![图片](https://github.com/Richasy/RichasyAssistant/assets/77724796/041ecea9-c168-4e8c-8de5-45b5cab4a7b7)

### Application source / 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] Others / 其它

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [X] Others / 其它

### Other system versions / 其它系统版本

Windows 11 23H2 (22631.2861)

### Device / 运行设备

Tablet/平板或笔记本

### We are the world / 人人为我，我为人人

None

**Comment by Richasy** [comment]
不太明白你说的 `自部署 Open API` 是什么意思...

**Comment by Alwaysbesideyou** [comment]
#14 已经修复了。
![image](https://github.com/Richasy/RichasyAssistant/assets/62324232/5a64e6d7-ec0a-42f7-933f-330aa49c8cc6)

这个“自部署API”是将各种模型使用遵循标准的 OpenAI API 格式进行访问。项目是[https://github.com/songquanpeng/one-api](url)
